version: '3.8'
services:
  neo4j:
    image: neo4j:5.19
    container_name: neo4j
    restart: always
    environment:
      NEO4J_AUTH: neo4j/testpassword
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data

volumes:
  neo4j_data:
